### PR TITLE
Fix deprecated warning using mongodb extension 1.20 or greater in ReadPrederence::getMode()

### LINKED ISSUE #185: Deprecated ReadPreference::getMode
According to the official documentation, the getMode() has been deprecated and will be removed in version 2.0 of MongoDB extension.

Usage on file _src/Capsule/Collection.php_, method `translateReadPreference` (line 210)

I suggest refactor translateReadPreference method to the following one:
```
    private function readPreferenceMode(ReadPreference $readPreference): string
    {
        return $readPreference->getModeString();
    }
```

Reference: https://www.php.net/manual/es/mongodb-driver-readpreference.getmode.php

### PR DESCRIPTION
**Pull request by Vegeeto**
Steps to reproduce:
1. Add the following option to makefile
```
.PHONY: setup-74-mongo-5
setup-74-mongo-5: PHP_VERSION=7.4
setup-74-mongo-5: MONGODB_EXTENSION_VERSION=1.20.0
setup-74-mongo-5: MONGODB_VERSION=5.0
setup-74-mongo-5: | --build --setup-common
```
2. Enter to the container: `make sh`
3. Execute unit tests: `make tests`

Added a mongodb version check in order to use _getModeString()_ method instead of calling _getMode()_
Added tests to check

PS: I don't like so much the way I tested it. If you have any suggestion, please feel free to comment it. Thanks!

Resolves #185 https://github.com/facile-it/mongodb-bundle/issues/185

### CODE REVIEW

File: src/Capsule/Collection.php [hunk 1]
```diff
@@ -206,6 +206,10 @@ private function prepareQuery(string $method, $filters, $data, array $options):
 
     private function translateReadPreference(ReadPreference $readPreference): string
     {
+        if (version_compare(phpversion('mongodb'), '1.20.0', '>=')) {
+            return $readPreference->getModeString();
+        }
```
Comment (Jean85) [inline src/Capsule/Collection.php:211]: Couldn't you check for the existence of the method? It should be faster and clearer.
```suggestion
        if (method_exists(ReadPreference::class, 'getModeString')) {
            return $readPreference->getModeString();
        }
```

**Comment by ilario-pierbattista** [comment]
> PS: I don't like so much the way I tested it. If you have any suggestion, please feel free to comment it. Thanks!

hey @Vegeeto, why don't you add an item with that configuration here? https://github.com/facile-it/mongodb-bundle/blob/master/.github/workflows/ci.yaml#L29

File: tests/Unit/Capsule/DatabaseTest.php [hunk 2]
```diff
@@ -33,8 +33,12 @@ public function test_selectCollection(): void
         self::assertEquals('testdb', $debugInfo['databaseName']);
     }
 
-    public function test_withOptions(): void
+    public function test_withOptions_using_mongodb_extension_lower_than_1_20_0(): void
```
Comment (ilario-pierbattista) [inline tests/Unit/Capsule/DatabaseTest.php:36]: I wouldn't make those test mutually exclusive. 

As far as I see, the only thing that changes is the way to get the readPreference and make assertions on it. 
I would extract a method that get it which apply takes the extension version into account.

Comment (Vegeeto) [reply tests/Unit/Capsule/DatabaseTest.php]: Done! Thanks for the suggestion :)
#[Commit link](https://github.com/facile-it/mongodb-bundle/pull/187/commits/ef15b4de9fc361d2bc794b2c6a0bbcaa1dfe3922)

**Comment by ilario-pierbattista** [comment]
thank you @Vegeeto, released in https://github.com/facile-it/mongodb-bundle/releases/tag/1.6.1
